### ISSUE TITLE
Multiple bugs

### ISSUE THREAD

**Issue by SlimJim192** [karliuka/m2.IndexerUrlRewrite#1]
Hi there,

Tried this module on magento 2.1.9 using your latest release version 2.0.3

product_url_rewrite =  "Product URL rewrites index is locked by another reindex process. Skipping."

tried resetting and running indexer, but the whole thing wont run with this module installed.

The other two commands and the generic reindex command gives me the result:

"Invalid XML in file /home/#######/########/public_html/app/code/Faonni/IndexerUrlRewrite/etc/mview.xml:
Element 'subscriptions': Missing child element(s). Expected is ( table ).
Line: 27"

**Comment by karliuka** [comment]
Hi,

Please, reset indexer state use sql query

Update `indexer_state` 
SET `status`='valid' 
WHERE `indexer_id` IN('product_url_rewrite','category_url_rewrite','cms_page_url_rewrite')

Run only product url reindexer

php bin/magento indexer:reindex product_url_rewrite

My need to know the result of these steps and how much products, Thank You
